### ISSUE TITLE
Blocked user

### ISSUE THREAD

**Issue by ThibeVL** [VendorAttestation/DiscordDMNukerV2#1]
Hello, if ur blocked or not friends you cant use this

**Comment by TheVisual** [comment]
> Hello, if ur blocked or not friends you cant use this

Hello what solution you propose?

**Comment by ThibeVL** [comment]
I never used selfbot before, is there an option to check on red text maybe?

**Comment by TheVisual** [comment]
> I never used selfbot before, is there an option to check on red text maybe?

Will look into this soon no ETA

**Comment by VendorAttestation** [comment]
@ThibeVL https://github.com/VendorAttestation/undiscord-reborn

Archiving this repo
